//generated by ../Checked/makeverilog.m 

assign node[0] = 28'h0000000; 
assign intcpt[0] = 28'h0000000; 

assign node[1] = 28'h00CCCCC; 
assign intcpt[1] = 28'h00CBFF4; 

assign node[2] = 28'h2000000; 
assign intcpt[2] = 28'h092FFFA; 

assign node[3] = 28'h2100000; 
assign intcpt[3] = 28'h0831A3E; 

assign node[4] = 28'h4000000; 
assign intcpt[4] = 28'h1234656; 

assign node[5] = 28'h6000000; 
assign intcpt[5] = 28'h1E0C862; 

assign node[6] = 28'h8000000; 
