	//generated by ../Checked/makeverilog.m 

	assign node[0] = 28'h0000000; 
	assign intcpt[0] = 28'h0000000; 

	assign node[1] = 28'h0400000; 
	assign intcpt[1] = 28'h0030000; 

	assign node[2] = 28'h0C00000; 
	assign intcpt[2] = 28'h01A0000; 

	assign node[3] = 28'h1C00000; 
	assign intcpt[3] = 28'h0520000; 

	assign node[4] = 28'h2C00000; 
	assign intcpt[4] = 28'h0AB0000; 

	assign node[5] = 28'h3000000; 
	assign intcpt[5] = 28'h0AF0000; 

	assign node[6] = 28'h4000000; 
	assign intcpt[6] = 28'h0AD0000; 

	assign node[7] = 28'h4400000; 
	assign intcpt[7] = 28'h1350000; 

	assign node[8] = 28'h4800000; 
	assign intcpt[8] = 28'h1390000; 

	assign node[9] = 28'h6000000; 
	assign intcpt[9] = 28'h1340000; 

	assign node[10] = 28'h6400000; 
	assign intcpt[10] = 28'h1FD0000; 

	assign node[11] = 28'h6C00000; 
	assign intcpt[11] = 28'h2020000; 

	assign node[12] = 28'h7C00000; 
	assign intcpt[12] = 28'h2000000; 

	assign node[13] = 28'h8000000; 
